version: '3.8'
services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium-container
    ports:
      - "4444:4444"
    networks:
      - app-network
    environment:
      - SE_ENABLE_TRACING=false 

  app:
    build: .
    container_name: flask-app
    ports:
      - "8080:8080"
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=selenium-container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge





